#!/bin/bash
# Source OS detection and common functions
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/os-detect.sh"

# Print OS information
SCRIPT_NAME=$(basename "$0")
echo "=========================================="
echo "$SCRIPT_NAME - LCD Installation"
echo "=========================================="
echo "Detected OS: $DETECTED_OS"
echo "Boot Path: $BOOT_PATH"
echo "Overlays Path: $OVERLAYS_PATH"
echo "=========================================="

sudo cp -rf ./boot/config-35DPI.txt /boot/config.txt
#sudo cp ./usr/bcm2709-rpi-2-b.dtb /boot/
#sudo cp ./usr/bcm2710-rpi-3-b.dtb /boot/ 
#sudo cp ./usr/cmdline.txt /boot/
#sudo cp ./usr/qddpi24.dtb "$OVERLAYS_PATH/"
#sudo cp ./usr/qddpi24.dtb "$OVERLAYS_PATH/"qddpi24.dtbo
#sudo cp ./usr/inittab /etc/
#sudo cp -rf ./usr/99-fbturbo.conf-HDMI /usr/share/X11/xorg.conf.d/99-fbturbo.conf 
sudo mkdir -p /etc/X11/xorg.conf.d 
sudo cp -rf ./usr/99-calibration.conf-3508 /etc/X11/xorg.conf.d/99-calibration.conf 
nodeplatform=`uname -n`
kernel=`uname -r`
version=`uname -v`
if test "$nodeplatform" = "raspberrypi";then
echo "this is raspberrypi kernel"
version=${version%% *}
version=${version#*#}
echo $version
if test $version -lt 970;then
echo "reboot"
else
echo "need to update touch configuration"
sudo apt-get install xserver-xorg-input-evdev
sudo cp -rf /usr/share/X11/xorg.conf.d/10-evdev.conf /usr/share/X11/xorg.conf.d/45-evdev.conf
echo "reboot"
fi
else
echo "this is not raspberrypi kernel, no need to update touch configure, reboot"
fi
sudo reboot
